version: "3.6"
services:
  server:
    container_name: app_server
    restart: always
    image: server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app/backend
      - ./frontend/dist:/app/dist
    networks:
      - cedalo-platform

networks:
  cedalo-platform:
    name: cedalo-platform
    driver: bridge
