version: "3.6"
services:
  activemq:
    image: rmohr/activemq
    ports:
      - 1883:1883
      - 61616:61616
      - 8161:8161
    networks:
      - cedalo-platform
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: always
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    environment:
      - TZ=Europe/Kiev
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
networks:
  cedalo-platform:
    name: cedalo-platform
    driver: bridge
