version: "3.6"
services:
  activemq:
    image: rmohr/activemq
    ports:
      - 1883:1883
      - 61616:61616
      - 8161:8161
    networks:
      - cedalo-platform
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: always
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    environment:
      - TZ=Europe/Kiev
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ../store/mysql_data:/var/lib/mysql
    networks:
      - cedalo-platform
networks:
  cedalo-platform:
    name: cedalo-platform
    driver: bridge
