version: "3.6"
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ../store/mysql_data:/var/lib/mysql
    networks:
      - server-net

networks:
  server-net:
    name: server-net
    driver: bridge
