version: "3.6"
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: always
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    environment:
      - TZ=Europe/Kiev
    devices:
      - /dev/ttyAML0:/dev/ttyACM0
  app:
    container_name: app_server
    restart: always
    image: server
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ../frontend:/frontend
      - ../backend:/backend
    networks:
      - cedalo-platform
networks:
  cedalo-platform:
    name: cedalo-platform
    driver: bridge
