version: "3.6"
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: always
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    environment:
      - TZ=Europe/Kiev
    devices:
      - /dev/ttyAML0:/dev/ttyACM0
  server:
    container_name: app_server
    restart: always
    image: server
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../backend:/app/backend
      - ../frontend/dist:/app/dist
      - ../store:/app/store
    networks:
      - cedalo-platform
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ../store/mysql_data:/var/lib/mysql
    networks:
      - cedalo-platform
networks:
  cedalo-platform:
    name: cedalo-platform
    driver: bridge
