version: "3.6"
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: always
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    environment:
      - TZ=Europe/Kiev
    devices:
      - /dev/ttyAML0:/dev/ttyACM0
  server:
    container_name: app_server
    restart: always
    image: server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
        - 3000:3000
    volumes:
        - ../backend:/app/backend
        - ../frontend/dist:/app/dist
    networks:
      - cedalo-platform
networks:
  cedalo-platform:
    name: cedalo-platform
    driver: bridge
